// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ReverseGeocode
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("zipcode")]
        public long? Zipcode { get; set; }

        [JsonProperty("state_abbr")]
        public string StateAbbr { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("distance")]
        public double? Distance { get; set; }

        [JsonProperty("latitudeClosest")]
        public string LatitudeClosest { get; set; }

        [JsonProperty("longitudeClosest")]
        public string LongitudeClosest { get; set; }

        [JsonProperty("countryCode")]
        public string CountryCode { get; set; }

        [JsonProperty("latitude")]
        public double? Latitude { get; set; }

        [JsonProperty("longitude")]
        public double? Longitude { get; set; }

        [JsonProperty("estimatedCity")]
        public bool? EstimatedCity { get; set; }

        [JsonProperty("nearestCities")]
        public string[] NearestCities { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
